/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cgu`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Maps` | `/Maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Trajets` | `/Trajets`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/Login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/Register`; params?: Router.UnknownInputParams; } | { pathname: `/services/TransportService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatters`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cgu`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(TabBar)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(TabBar)'}/Maps` | `/Maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(TabBar)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(TabBar)'}/Trajets` | `/Trajets`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/services/TransportService`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/formatters`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cgu${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(TabBar)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(TabBar)'}/Maps${`?${string}` | `#${string}` | ''}` | `/Maps${`?${string}` | `#${string}` | ''}` | `${'/(TabBar)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `${'/(TabBar)'}/Trajets${`?${string}` | `#${string}` | ''}` | `/Trajets${`?${string}` | `#${string}` | ''}` | `/authentication/Login${`?${string}` | `#${string}` | ''}` | `/authentication/Register${`?${string}` | `#${string}` | ''}` | `/services/TransportService${`?${string}` | `#${string}` | ''}` | `/utils/formatters${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cgu`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Maps` | `/Maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(TabBar)'}/Trajets` | `/Trajets`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/Login`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/Register`; params?: Router.UnknownInputParams; } | { pathname: `/services/TransportService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatters`; params?: Router.UnknownInputParams; };
    }
  }
}
